# -*- coding: utf-8 -*-
"""Room_simulation_2D.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EDDokFY19r68fl4wzYft59RTWOU5qIL_

### **部屋の空気の流れの式**
$$\frac{∂u​}{∂t}+c_x\frac{∂u}{∂x}+c_y\frac{∂u}{∂y}=v(\frac{∂^2u}{∂x^2}+\frac{∂^2u}{∂y^2})$$

赤→強い空気が入るところ
青→弱い空気

GIFダウンロード
"""

pip install imageio

"""横の移動（右方向）"""

(un[j, i] - un[j, i-1])

"""縦の移動（下方向）"""

(un[j, i] - un[j-1, i])

"""横の拡散"""

(un[j, i+1] - 2*un[j, i] + un[j, i-1])

"""縦の拡散"""

(un[j+1, i] - 2*un[j, i] + un[j-1, i])

"""**部屋の空気の流れ**"""

import numpy as np
import matplotlib.pyplot as plt
import imageio

nx, ny = 50, 50
nt = 130
c = 2.0
nu = 0.01

dx = 2 / (nx - 1)
dy = 2 / (ny - 1)
dt = 0.01

# 初期状態
u = np.ones((ny, nx))

# 左から流入
u[:, 0:5] = 1.5

plt.ioff()
fig, ax = plt.subplots()

frames = []

for n in range(nt):
    un = u.copy()

    for j in range(1, ny-1):
        for i in range(1, nx-1):

            # 基本の移流＋拡散
            u[j, i] = (
                un[j, i]
                - c * dt/dx * (un[j, i] - un[j, i-1])
                - c * dt/dy * (un[j, i] - un[j-1, i])
                + nu * dt/dx**2 * (un[j, i+1] - 2*un[j, i] + un[j, i-1])
                + nu * dt/dy**2 * (un[j+1, i] - 2*un[j, i] + un[j-1, i])
            )

    # 描画
    ax.clear()
    ax.imshow(u, cmap='coolwarm')
    ax.set_title(f"Step {n}")

    # フレーム保存
    fig.canvas.draw()
    image = np.array(fig.canvas.renderer.buffer_rgba())
    image = image[:, :, :3]

    if n % 3 == 0:
        frames.append(image)

# GIF保存
imageio.mimsave('simulation.gif', frames, fps=5)

plt.close()

print("GIF保存完了: simulation.gif")

from IPython.display import Image
Image("simulation.gif")

from google.colab import files
files.download('simulation.gif')

"""**壁を設置する**"""

import numpy as np
import matplotlib.pyplot as plt
import imageio

nx, ny = 50, 50
nt = 130
c = 2.0
nu = 0.01

dx = 2 / (nx - 1)
dy = 2 / (ny - 1)
dt = 0.01

# 初期状態
u = np.ones((ny, nx))
wall = np.zeros((ny, nx))

# 壁（中央）
wall[:, nx//2] = 1

# 穴（必要なら消すと完全な壁）
# wall[20:22, nx//2] = 0
# wall[28:30, nx//2] = 0

# 左から流入
u[:, 0:5] = 1.5

plt.ioff()
fig, ax = plt.subplots()

frames = []

for n in range(nt):
    un = u.copy()

    for j in range(1, ny-1):
        for i in range(1, nx-1):

            # 壁の中は固定
            if wall[j, i] == 1:
                u[j, i] = 1
                continue

            # 周囲の壁チェック
            left_wall  = wall[j, i-1] == 1
            right_wall = wall[j, i+1] == 1
            up_wall    = wall[j-1, i] == 1
            down_wall  = wall[j+1, i] == 1

            # 移流（壁なら止める）
            adv_x = 0 if left_wall else c * dt/dx * (un[j, i] - un[j, i-1])
            adv_y = 0 if up_wall   else c * dt/dy * (un[j, i] - un[j-1, i])

            # 拡散（壁の影響を考慮）
            diff_x = 0
            if not left_wall and not right_wall:
                diff_x = nu * dt/dx**2 * (un[j, i+1] - 2*un[j, i] + un[j, i-1])

            diff_y = 0
            if not up_wall and not down_wall:
                diff_y = nu * dt/dy**2 * (un[j+1, i] - 2*un[j, i] + un[j-1, i])

            # 更新
            u[j, i] = un[j, i] - adv_x - adv_y + diff_x + diff_y

    # 描画
    ax.clear()
    display = u.copy()
    display[wall == 1] = 0

    ax.imshow(display, cmap='coolwarm')
    ax.set_title(f"Step {n}")

    # フレーム保存
    fig.canvas.draw()
    image = np.array(fig.canvas.renderer.buffer_rgba())
    image = image[:, :, :3]

    if n % 3 == 0:
        frames.append(image)

# GIF保存
imageio.mimsave('simulation_wall.gif', frames, fps=5)

plt.close()

print("GIF保存完了: simulation_wall.gif")

from IPython.display import Image
Image("simulation_wall.gif")

from google.colab import files
files.download('simulation_wall.gif')

"""**壁に穴をあける**"""

import numpy as np
import matplotlib.pyplot as plt
import imageio

nx, ny = 50, 50
nt = 130
c = 2.0
nu = 0.01

dx = 2 / (nx - 1)
dy = 2 / (ny - 1)
dt = 0.01

# 初期状態
u = np.ones((ny, nx))
wall = np.zeros((ny, nx))

# 壁（中央に設置）
wall[:, nx//2] = 1

# 壁に穴
wall[20:22, nx//2] = 0
wall[28:30, nx//2] = 0

# 左から流入
u[:, 0:5] = 1.5

plt.ioff()
fig, ax = plt.subplots()

frames = []

for n in range(nt):
    un = u.copy()

    for j in range(1, ny-1):
        for i in range(1, nx-1):

            # 壁の中は固定
            if wall[j, i] == 1:
                u[j, i] = 1
                continue

            # 左が壁ならスキップ
            if wall[j, i-1] == 1:
                continue

            # 移流＋拡散
            u[j, i] = (
                un[j, i]
                - c * dt/dx * (un[j, i] - un[j, i-1])
                - c * dt/dy * (un[j, i] - un[j-1, i])
                + nu * dt/dx**2 * (un[j, i+1] - 2*un[j, i] + un[j, i-1])
                + nu * dt/dy**2 * (un[j+1, i] - 2*un[j, i] + un[j-1, i])
            )

    # 描画
    ax.clear()
    display = u.copy()
    display[wall == 1] = 0

    ax.imshow(display, cmap='coolwarm')
    ax.set_title(f"Step {n}")

    # フレーム保存
    fig.canvas.draw()
    image = np.array(fig.canvas.renderer.buffer_rgba())
    image = image[:, :, :3]

    if n % 3 == 0:
        frames.append(image)

# GIF保存
imageio.mimsave('simulation_wall_hole.gif', frames, fps=5)

plt.close()

print("GIF保存完了: simulation_wall_hole.gif")

from IPython.display import Image
Image("simulation_wall_hole.gif")

from google.colab import files
files.download('simulation_wall_hole.gif')

"""**ドライブに保存**"""

from google.colab import drive
drive.mount('/content/drive')